"""Tests for the generator/detach/regenerate round-trip invariants:
tools/vs2_scene_gen/{generator,detach,regenerate,checksum,blob}.py.

Pure CPython, no MicroPython shims -- this pipeline never runs on-device.
Run: ``python3 tests/test_vs2_scene_gen_generator.py``.
"""

import json
import os
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from tools.vs2_scene_gen import checksum, detach, generator, regenerate


def _small_model():
    return {
        "version": 1,
        "class_name": "DemoScene",
        "layers": [
            {
                "attr": "world",
                "drawables": [
                    {"kind": "sprite", "attr": "hero", "image": "hero.png", "x": 3, "y": 4},
                    {
                        "kind": "sprite_pool",
                        "attr": "shots",
                        "image": "shot.png",
                        "count": 4,
                        "behaviors": [{"class": "Moving", "params": {"speed_y": -2}}],
                    },
                ],
            }
        ],
    }


class GeneratorFixture(unittest.TestCase):
    def setUp(self):
        self.tmpdir = Path(tempfile.mkdtemp(prefix="vs2_scene_gen_test_"))
        self.addCleanup(shutil.rmtree, self.tmpdir, ignore_errors=True)

    def output_path(self, name="demo_scene.py"):
        return self.tmpdir / name


class ByteIdenticalRegenerationTests(GeneratorFixture):
    def test_second_write_reports_unchanged_and_is_byte_identical(self):
        model = _small_model()
        path = self.output_path()

        first = generator.write_scene_file(model, path)
        self.assertEqual(first.status, "created")
        first_bytes = path.read_bytes()

        second = generator.write_scene_file(model, path)
        self.assertEqual(second.status, "unchanged")
        self.assertEqual(path.read_bytes(), first_bytes)

    def test_regenerating_from_an_equivalent_model_dict_is_still_byte_identical(self):
        # Dict key/insertion order must not leak into the generated bytes --
        # blob.encode_blob sorts keys precisely so this holds.
        model = _small_model()
        path = self.output_path()
        generator.write_scene_file(model, path)
        first_bytes = path.read_bytes()

        reordered = json.loads(json.dumps(model))  # fresh dict, same content
        result = generator.write_scene_file(reordered, path)
        self.assertEqual(result.status, "unchanged")
        self.assertEqual(path.read_bytes(), first_bytes)


class HandEditDetectionTests(GeneratorFixture):
    def test_editing_the_body_is_detected_and_the_file_is_left_alone(self):
        model = _small_model()
        path = self.output_path()
        generator.write_scene_file(model, path)
        original_text = path.read_text()

        # Edit something inside the body (between banner and blank-line
        # separator), leaving the banner's recorded checksum stale.
        edited = original_text.replace(
            "class DemoScene(vs2.Scene):", "class DemoScene(vs2.Scene):  # tweaked"
        )
        self.assertNotEqual(edited, original_text)
        path.write_text(edited)

        result = generator.write_scene_file(model, path)
        self.assertEqual(result.status, "hand_edited")
        self.assertEqual(path.read_text(), edited, "hand-edited file must not be overwritten")

    def test_checksum_is_hand_edited_predicate_agrees(self):
        model = _small_model()
        path = self.output_path()
        generator.write_scene_file(model, path)
        text = path.read_text()
        self.assertFalse(checksum.is_hand_edited(text))

        edited = text.replace("pass", "pass  # noop", 1)
        self.assertTrue(checksum.is_hand_edited(edited))


class DetachSurvivesRegenerateTests(GeneratorFixture):
    def test_detached_file_is_not_overwritten_by_a_later_sweep(self):
        model = _small_model()
        model_path = self.tmpdir / "demo_scene.vs2model.json"
        model_path.write_text(json.dumps(model))
        output_path = regenerate.output_path_for(model_path)

        first = regenerate.regenerate_all(self.tmpdir)
        self.assertEqual([r.status for r in first], ["created"])

        detached_text = detach.detach_file(output_path)
        self.assertFalse(detach.is_generated(detached_text))

        second = regenerate.regenerate_all(self.tmpdir)
        self.assertEqual([r.status for r in second], ["detached"])
        self.assertEqual(output_path.read_text(), detached_text)

    def test_detach_is_one_way_raises_on_already_detached_text(self):
        model = _small_model()
        path = self.output_path()
        generator.write_scene_file(model, path)
        once = detach.detach_file(path)
        self.assertFalse(detach.is_generated(once))
        with self.assertRaises(detach.DetachError):
            detach.detach(once)


class CompanionStubTests(GeneratorFixture):
    def test_creates_stub_only_when_missing_then_leaves_it_alone(self):
        model = _small_model()
        model["layers"][0]["drawables"][1]["behaviors"][0]["params"]["on_end"] = {
            "handler": "shots_died"
        }
        companion_path = self.tmpdir / "demo.py"

        first = regenerate.ensure_companion_stub(
            model, "demo_scene", "DemoScene", "Demo", companion_path)
        self.assertEqual(first.status, "created")
        self.assertEqual(first.handlers, ["shots_died"])
        self.assertTrue(companion_path.exists())
        original_text = companion_path.read_text()

        # A later regeneration (even with a changed model) must not touch it.
        model["layers"][0]["drawables"][1]["behaviors"][0]["params"]["on_end"] = {
            "handler": "a_totally_different_handler"
        }
        second = regenerate.ensure_companion_stub(
            model, "demo_scene", "DemoScene", "Demo", companion_path)
        self.assertEqual(second.status, "left_alone")
        self.assertEqual(companion_path.read_text(), original_text)


class HookNumberingTests(GeneratorFixture):
    def test_hook_count_matches_number_of_drawables(self):
        model = _small_model()
        self.assertEqual(generator.hook_count(model), 2)

    def test_body_defines_hook_count_plus_one_hooks(self):
        model = _small_model()
        body = generator.render_body(model)
        for index in range(generator.hook_count(model) + 1):
            self.assertIn("def on_build_%d(self):" % index, body)
        self.assertNotIn("def on_build_3(self):", body)


if __name__ == "__main__":
    unittest.main()
