VENTILASTATION_MODULES=`pwd`/modules/micropython.cmake
FROZEN_MANIFEST=`pwd`/../../apps/micropython/manifest.py

cd micropython/ports/esp32

BOARD=ESP32_GENERIC_S3
BOARD_VARIANT=SPIRAM_OCT
BAUD=1500000

#BOARD=ESP32_GENERIC
#BOARD_VARIANT=SPIRAM_OCT
#PORT=/dev/cu.usbserial-0001
PORT=/dev/cu.usbmodem14301
#PORT=/dev/cu.usbmodem585A0473901
#BAUD=1500000

PARAMS="V=1 BOARD=$BOARD BOARD_VARIANT=$BOARD_VARIANT PORT=$PORT BAUD=$BAUD USER_C_MODULES=$VENTILASTATION_MODULES FROZEN_MANIFEST=$FROZEN_MANIFEST"
#make $PARAMS clean
make $PARAMS $1
#make $PARAMS deploy
