#!/usr/bin/env python3
"""Convert tinyfont_white.png into a compact compiled-C glyph table.

Each glyph is 4x6px in the source strip but only the left 3 columns and all
6 rows are ever lit (verified against the full 128-frame strip), so every
glyph is packed into a single byte: bit 2 = column 0 (leftmost), bit 1 =
column 1, bit 0 = column 2. One byte per row, 6 bytes per glyph.

Used by the Ventilastation POV native dialog renderer
(components/retro-go/drivers/display/ventilastation_pov.c), which draws
text directly in polar (angle, radius) space and has no use for retro-go's
heavier rg_font_t format (8px+ tall, proportional, per-glyph headers) —
those glyphs don't fit the POV's 54-LED radius legibly.
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "system" / "shared" / "other" / "images" / "tinyfont_white.png"
OUT = ROOT / "apps" / "retro-go" / "components" / "retro-go" / "drivers" / "display" / "tinyfont_data.h"
GLYPH_WIDTH = 4
GLYPH_HEIGHT = 6
NUM_GLYPHS = 128
COLUMNS_USED = 3


def glyph_rows(img, ch):
    crop = img.crop((ch * GLYPH_WIDTH, 0, ch * GLYPH_WIDTH + GLYPH_WIDTH, GLYPH_HEIGHT))
    px = list(crop.getdata())
    rows = []
    for y in range(GLYPH_HEIGHT):
        byte = 0
        for x in range(COLUMNS_USED):
            r, g, b, a = px[y * GLYPH_WIDTH + x]
            if a > 0 and r > 0:
                byte |= 1 << (COLUMNS_USED - 1 - x)
        rows.append(byte)
    return rows


def main():
    img = Image.open(SRC).convert("RGBA")
    expected = (GLYPH_WIDTH * 256, GLYPH_HEIGHT)
    if img.size != expected:
        raise ValueError("tinyfont_white.png must be %s, got %s" % (expected, img.size))

    for ch in range(NUM_GLYPHS):
        for y, byte in enumerate(glyph_rows(img, ch)):
            if byte & ~((1 << COLUMNS_USED) - 1):
                raise ValueError(f"glyph {ch} row {y} uses more than {COLUMNS_USED} columns")

    lines = [
        "// Generated by tools/generate_tinyfont_c.py from tinyfont_white.png. Do not edit by hand.",
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        f"#define TINYFONT_GLYPH_WIDTH {COLUMNS_USED}",
        f"#define TINYFONT_GLYPH_HEIGHT {GLYPH_HEIGHT}",
        f"#define TINYFONT_NUM_GLYPHS {NUM_GLYPHS}",
        "",
        "// One byte per row; bit (TINYFONT_GLYPH_WIDTH-1-x) set = pixel x lit.",
        "// Indexed by ASCII code point (0..127); unprintable codes are blank.",
        f"static const uint8_t tinyfont_glyphs[TINYFONT_NUM_GLYPHS][TINYFONT_GLYPH_HEIGHT] = {{",
    ]
    for ch in range(NUM_GLYPHS):
        rows = glyph_rows(img, ch)
        row_str = ", ".join(f"0x{b:02x}" for b in rows)
        comment = repr(chr(ch)) if 32 <= ch < 127 else f"0x{ch:02x}"
        lines.append(f"    {{{row_str}}}, // {ch} {comment}")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
