#!/usr/bin/env python3
"""One-command setup, supervisor, and smoke test for the remote workbench."""

from __future__ import annotations

import argparse
import glob
import json
import os
from pathlib import Path
import re
import secrets
import shlex
import shutil
import sqlite3
import subprocess
import sys
import time
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.parse import urlencode, urlsplit
from urllib.request import HTTPRedirectHandler, build_opener, urlopen
import venv
import webbrowser


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ORIGIN = "https://ventilastation.protocultura.net"
DEFAULT_RELAY_GATEWAY = "https://ventilastation-board.protocultura.net"
DEFAULT_TELEMETRY_HOST = "192.168.1.100"
DEFAULT_NGROK_AUTH_ID = "vsdk-remote-workbench"
EMAIL_PATTERN = re.compile(r"^[A-Za-z0-9.!#$%&*+/=?^_`{|}~-]+@[A-Za-z0-9.-]+$")
REQUIRED_ENV = (
    "REMOTE_WORKBENCH_BOARD",
    "REMOTE_WORKBENCH_TICKET_AUDIENCE",
    "REMOTE_WORKBENCH_TICKET_KEY_FILE",
    "REMOTE_WORKBENCH_STATE_DB",
    "REMOTE_WORKBENCH_SERIAL_PORT",
    "REMOTE_WORKBENCH_ALLOWED_ORIGINS",
)


def default_config_dir() -> Path:
    base = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return base / "vsdk" / "remote-workbench"


def venv_python(config_dir: Path) -> Path:
    windows = config_dir / "venv" / "Scripts" / "python.exe"
    return windows if windows.exists() else config_dir / "venv" / "bin" / "python"


def validate_email(value: str) -> str:
    email = value.strip().casefold()
    if not EMAIL_PATTERN.fullmatch(email):
        raise ValueError("a valid --email is required")
    return email


def validate_auth_id(value: str) -> str:
    auth_id = value.strip()
    if not re.fullmatch(r"[A-Za-z0-9._-]+", auth_id):
        raise ValueError("--ngrok-auth-id may contain only letters, digits, dot, underscore, and dash")
    return auth_id


def find_serial_port(explicit: str = "auto") -> str:
    if explicit and explicit != "auto":
        return explicit
    matches: list[str] = []
    for pattern in ("/dev/cu.usbmodem*", "/dev/ttyACM*", "/dev/ttyUSB*"):
        matches.extend(glob.glob(pattern))
    matches = sorted(set(matches))
    if len(matches) == 1:
        return matches[0]
    if not matches:
        return "auto"
    raise RuntimeError("multiple USB serial devices found; pass --serial-port: %s" % ", ".join(matches))


def _write_private(path: Path, content: str, overwrite: bool = False) -> None:
    if path.exists() and not overwrite:
        raise FileExistsError("%s already exists (use --force to replace generated configuration)" % path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(0o600)
    temporary.replace(path)


def _env_line(name: str, value: str | Path | int) -> str:
    return "export %s=%s" % (name, shlex.quote(str(value)))


def render_environment(config_dir: Path, serial_port: str, telemetry_host: str, origin: str) -> str:
    values = {
        "REMOTE_WORKBENCH_BOARD": "workbench-1",
        "REMOTE_WORKBENCH_TICKET_AUDIENCE": "ventilastation-remote-workbench",
        "REMOTE_WORKBENCH_TICKET_KEY_FILE": config_dir / "ticket.key",
        "REMOTE_WORKBENCH_STATE_DB": config_dir / "state.sqlite3",
        "REMOTE_WORKBENCH_HOST": telemetry_host,
        "REMOTE_WORKBENCH_PORT": 5005,
        "REMOTE_WORKBENCH_SERIAL_PORT": serial_port,
        "REMOTE_WORKBENCH_ALLOWED_ORIGINS": origin,
        "REMOTE_WORKBENCH_BIND": "127.0.0.1",
        "REMOTE_WORKBENCH_BIND_PORT": 8765,
        "REMOTE_WORKBENCH_AUTH_MODE": "trusted-proxy",
        "REMOTE_WORKBENCH_TRUSTED_EMAIL_HEADER": "X-Remote-Email",
        "REMOTE_WORKBENCH_TRUSTED_SUBJECT_HEADER": "X-Remote-Subject",
        "REMOTE_WORKBENCH_ICE_SERVERS_JSON": '[{"urls":["stun:stun.l.google.com:19302"]}]',
    }
    return "\n".join(_env_line(name, value) for name, value in values.items()) + "\n"


def render_ngrok_policy(email: str, auth_id: str) -> str:
    return """# Generated by tools/remote_workbench.py. Keep this file private.
on_http_request:
  - expressions:
      - 'req.url.path != "/ws"'
    actions:
      - type: oauth
        config:
          provider: google
          auth_id: %s
          idle_session_timeout: 15m
          max_session_duration: 1h
  - expressions:
      - 'req.url.path != "/ws" && !(actions.ngrok.oauth.identity.email in [''%s''])'
    actions:
      - type: deny
  - expressions:
      - 'req.url.path != "/ws"'
    actions:
      - type: remove-headers
        config:
          headers: [X-Remote-Email, X-Remote-Subject]
      - type: add-headers
        config:
          headers:
            X-Remote-Email: "${actions.ngrok.oauth.identity.email}"
""" % (auth_id, email)


def load_environment(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    for number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].strip()
        name, separator, raw_value = line.partition("=")
        if not separator or not name.strip():
            raise ValueError("invalid environment line %d in %s" % (number, path))
        values = shlex.split(raw_value, posix=True)
        if len(values) != 1:
            raise ValueError("invalid environment value on line %d in %s" % (number, path))
        result[name.strip()] = values[0]
    return result


def process_environment(config_dir: Path) -> dict[str, str]:
    environment = os.environ.copy()
    environment.update(load_environment(config_dir / "gateway.env"))
    environment["PYTHONUNBUFFERED"] = "1"
    return environment


def run_checked(command: list[str], **kwargs) -> None:
    print("+", shlex.join(command))
    subprocess.run(command, check=True, **kwargs)


def setup(args: argparse.Namespace) -> int:
    config_dir = args.config_dir.expanduser().resolve()
    email = validate_email(args.email)
    auth_id = validate_auth_id(args.ngrok_auth_id)
    existing_environment = config_dir / "gateway.env"
    if args.serial_port == "auto" and existing_environment.exists() and not args.force:
        serial_port = load_environment(existing_environment)["REMOTE_WORKBENCH_SERIAL_PORT"]
    else:
        serial_port = find_serial_port(args.serial_port)
    config_dir.mkdir(parents=True, exist_ok=True)
    config_dir.chmod(0o700)

    key_path = config_dir / "ticket.key"
    if not key_path.exists():
        _write_private(key_path, secrets.token_hex(32) + "\n")
    generated = (
        (config_dir / "gateway.env", render_environment(config_dir, serial_port, args.telemetry_host, args.origin)),
        (config_dir / "ngrok-policy.yml", render_ngrok_policy(email, auth_id)),
    )
    for path, content in generated:
        if path.exists() and not args.force:
            print("Reusing", path, "(pass --force to regenerate it)")
        else:
            _write_private(path, content, overwrite=args.force)

    if not args.skip_install:
        environment_dir = config_dir / "venv"
        if not venv_python(config_dir).exists():
            print("Creating isolated gateway environment at", environment_dir)
            venv.EnvBuilder(with_pip=True).create(environment_dir)
        run_checked([
            str(venv_python(config_dir)), "-m", "pip", "install", "-r",
            str(ROOT / "requirements-remote-workbench.txt"),
        ])
        environment = process_environment(config_dir)
        run_checked([
            str(venv_python(config_dir)), "-m", "emulator.remote_gateway",
            "acl", "grant", email, "controller",
        ], cwd=ROOT, env=environment)

    print("\nRemote workbench configured.")
    print("Next: ngrok config add-authtoken <token>")
    print("Then: make remote-workbench-run")
    return 0


def select_transport(config_dir: Path, requested: str = "auto") -> str:
    if requested != "auto":
        return requested
    if (config_dir / "frpc.toml").exists() and (config_dir / "bin" / "frpc").exists():
        return "frp"
    return "ngrok"


def public_gateway_url(config_dir: Path, explicit: str | None = None) -> str:
    gateway = explicit or os.environ.get("REMOTE_WORKBENCH_PUBLIC_GATEWAY") or DEFAULT_RELAY_GATEWAY
    parsed = urlsplit(gateway)
    if parsed.scheme != "https" or not parsed.hostname or parsed.username or parsed.password:
        raise ValueError("public gateway must be an HTTPS origin")
    if parsed.path not in {"", "/"} or parsed.query or parsed.fragment:
        raise ValueError("public gateway must not include a path, query, or fragment")
    return gateway.rstrip("/")


def doctor(config_dir: Path, quiet: bool = False, transport: str = "auto") -> dict[str, str]:
    config_dir = config_dir.expanduser().resolve()
    env_path = config_dir / "gateway.env"
    if not env_path.exists():
        raise RuntimeError("configuration is missing; run make remote-workbench-setup EMAIL=you@example.com")
    transport = select_transport(config_dir, transport)
    environment = process_environment(config_dir)
    missing = [name for name in REQUIRED_ENV if not environment.get(name)]
    if missing:
        raise RuntimeError("gateway.env is missing: %s" % ", ".join(missing))
    python = venv_python(config_dir)
    if not python.exists():
        raise RuntimeError("gateway environment is missing; rerun remote-workbench-setup")
    serial_setting = environment["REMOTE_WORKBENCH_SERIAL_PORT"]
    serial_port = Path(serial_setting)
    serial_present = serial_setting != "auto" and serial_port.exists()
    if transport == "frp":
        if not (config_dir / "frpc.toml").exists():
            raise RuntimeError("FRP client configuration is missing: %s" % (config_dir / "frpc.toml"))
        if not (config_dir / "bin" / "frpc").exists():
            raise RuntimeError("FRP client binary is missing: %s" % (config_dir / "bin" / "frpc"))
    else:
        if not (config_dir / "ngrok-policy.yml").exists():
            raise RuntimeError("ngrok policy is missing; rerun remote-workbench-setup")
        if shutil.which("ngrok") is None:
            raise RuntimeError("ngrok is not installed or not on PATH")
    result = subprocess.run(
        [str(python), "-m", "emulator.remote_gateway", "serve", "--check-config"],
        cwd=ROOT,
        env=environment,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip() or "gateway configuration failed")
    if not quiet:
        print("✓ configuration")
        if serial_present:
            print("✓ USB board", serial_port)
        else:
            print("⚠ USB board absent at %s; synthetic display mode will be used" % serial_setting)
        print("✓ gateway dependencies")
        print("✓ %s transport" % transport.upper())
    return environment


def doctor_command(args: argparse.Namespace) -> int:
    doctor(args.config_dir, transport=args.transport)
    return 0


def discover_ngrok_url(timeout: float = 20.0) -> str:
    deadline = time.monotonic() + timeout
    last_error: Exception | None = None
    while time.monotonic() < deadline:
        try:
            with urlopen("http://127.0.0.1:4040/api/tunnels", timeout=1) as response:
                payload = json.load(response)
            urls = [
                tunnel.get("public_url", "") for tunnel in payload.get("tunnels", [])
                if str(tunnel.get("public_url", "")).startswith("https://")
            ]
            if urls:
                return urls[0].rstrip("/")
        except (OSError, ValueError, URLError) as error:
            last_error = error
        time.sleep(0.25)
    raise RuntimeError("ngrok did not publish an HTTPS endpoint%s" % (": %s" % last_error if last_error else ""))


def emulator_url(gateway: str, origin: str = DEFAULT_ORIGIN) -> str:
    return "%s/emulator/?%s" % (
        origin.rstrip("/"),
        urlencode({"remote": "1", "gateway": gateway.rstrip("/")}),
    )


class _NoRedirect(HTTPRedirectHandler):
    def redirect_request(self, request, fp, code, message, headers, newurl):  # noqa: ANN001
        return None


def tunnel_warning(gateway: str) -> str | None:
    request_url = gateway.rstrip("/") + "/auth/start"
    try:
        response = build_opener(_NoRedirect).open(request_url, timeout=8)
        body = response.read(64 * 1024).decode("utf-8", "replace")
    except HTTPError as error:
        if 300 <= error.code < 400:
            return None
        body = error.read(64 * 1024).decode("utf-8", "replace")
    except (OSError, URLError) as error:
        return "could not probe the public endpoint: %s" % error
    if "ERR_NGROK_725" in body or "Network bandwidth exceeded" in body:
        return "ngrok account bandwidth is exhausted (ERR_NGROK_725)"
    return None


def _stop_process(process: subprocess.Popen) -> None:
    if process.poll() is not None:
        return
    process.terminate()
    try:
        process.wait(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.wait(timeout=2)


def supervise(args: argparse.Namespace) -> int:
    config_dir = args.config_dir.expanduser().resolve()
    transport = select_transport(config_dir, args.transport)
    environment = doctor(config_dir, transport=transport)
    python = venv_python(config_dir)
    bind_port = environment.get("REMOTE_WORKBENCH_BIND_PORT", "8765")
    logs = config_dir / "logs"
    logs.mkdir(exist_ok=True)
    gateway_log_path = logs / "gateway.log"
    transport_log_path = logs / ("frpc.log" if transport == "frp" else "ngrok.log")
    gateway_log = gateway_log_path.open("ab", buffering=0)
    transport_log = transport_log_path.open("ab", buffering=0)
    gateway = subprocess.Popen(
        [str(python), "-m", "emulator.remote_gateway", "serve"],
        cwd=ROOT,
        env=environment,
        stdout=gateway_log,
        stderr=subprocess.STDOUT,
    )
    if transport == "frp":
        transport_command = [str(config_dir / "bin" / "frpc"), "-c", str(config_dir / "frpc.toml")]
    else:
        transport_command = [
            "ngrok", "http", "127.0.0.1:%s" % bind_port,
            "--traffic-policy-file", str(config_dir / "ngrok-policy.yml"),
        ]
        if args.ngrok_config:
            transport_command.extend(["--config", str(args.ngrok_config.expanduser())])
    transport_process = subprocess.Popen(
        transport_command, stdout=transport_log, stderr=subprocess.STDOUT,
    )
    try:
        gateway_url = (
            public_gateway_url(config_dir, args.gateway)
            if transport == "frp"
            else discover_ngrok_url()
        )
        print("\nServices are running.")
        print("Gateway:", gateway_url)
        print("Open this on the test phone/computer:")
        print(emulator_url(gateway_url, environment["REMOTE_WORKBENCH_ALLOWED_ORIGINS"].split(",")[0]))
        print("Transport:", transport.upper())
        print("\nLogs:", gateway_log_path, "and", transport_log_path)
        warning = tunnel_warning(gateway_url)
        if warning:
            print("WARNING:", warning, file=sys.stderr)
        print("Press Ctrl-C to stop both services.")
        while True:
            for name, process, path in (
                ("gateway", gateway, gateway_log_path),
                (transport, transport_process, transport_log_path),
            ):
                code = process.poll()
                if code is not None:
                    raise RuntimeError("%s exited with status %d; see %s" % (name, code, path))
            time.sleep(0.5)
    except KeyboardInterrupt:
        print("\nStopping remote workbench...")
        return 0
    finally:
        _stop_process(transport_process)
        _stop_process(gateway)
        gateway_log.close()
        transport_log.close()


MILESTONES = (
    ("login", lambda action, detail: action in {"ticket_issue", "websocket_accept", "connect"}),
    ("H.264 video", lambda action, detail: action == "video_state" and detail == "connected"),
    ("control lease", lambda action, detail: action == "lease_grant"),
    ("joystick input", lambda action, detail: action == "input"),
    ("audio command", lambda action, detail: action == "host_event" and detail in {"sound", "music", "notes"}),
)


def update_milestones(
    completed: set[str], rows: Iterable[tuple[str, str]],
) -> list[str]:
    newly_completed: list[str] = []
    for action, detail in rows:
        for name, predicate in MILESTONES:
            if name not in completed and predicate(action, detail):
                completed.add(name)
                newly_completed.append(name)
    return newly_completed


def smoke(args: argparse.Namespace) -> int:
    config_dir = args.config_dir.expanduser().resolve()
    environment = process_environment(config_dir)
    state_path = Path(environment["REMOTE_WORKBENCH_STATE_DB"])
    if not state_path.exists():
        raise RuntimeError("gateway state database does not exist; start remote-workbench-run first")
    if args.gateway:
        gateway = public_gateway_url(config_dir, args.gateway)
    elif select_transport(config_dir) == "frp":
        gateway = public_gateway_url(config_dir)
    else:
        gateway = discover_ngrok_url(timeout=2)
    url = emulator_url(gateway, environment["REMOTE_WORKBENCH_ALLOWED_ORIGINS"].split(",")[0])
    warning = tunnel_warning(gateway)
    if warning:
        raise RuntimeError(warning)

    connection = sqlite3.connect(state_path)
    initial_row = connection.execute("SELECT COALESCE(MAX(rowid), 0) FROM audit").fetchone()[0]
    print("Open, sign in, request control, move the joystick, and change a menu item:\n")
    print(url, "\n")
    if args.open:
        webbrowser.open(url)

    try:
        completed: set[str] = set()
        cursor = initial_row
        deadline = time.monotonic() + args.timeout
        for name, _predicate in MILESTONES:
            print("[ ]", name)
        while time.monotonic() < deadline:
            rows = connection.execute(
                "SELECT rowid, action, detail FROM audit WHERE rowid > ? ORDER BY rowid",
                (cursor,),
            ).fetchall()
            if rows:
                cursor = rows[-1][0]
                for name in update_milestones(completed, ((row[1], row[2]) for row in rows)):
                    print("[✓]", name)
            if len(completed) == len(MILESTONES):
                print("\nSmoke test passed.")
                return 0
            time.sleep(0.5)
    finally:
        connection.close()
    missing = [name for name, _predicate in MILESTONES if name not in completed]
    print("\nSmoke test timed out; missing:", ", ".join(missing), file=sys.stderr)
    return 1


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config-dir", type=Path, default=default_config_dir())
    subparsers = parser.add_subparsers(dest="command", required=True)

    setup_parser = subparsers.add_parser("setup", help="one-time install and private configuration")
    setup_parser.add_argument("--email", required=True)
    setup_parser.add_argument("--serial-port", default="auto")
    setup_parser.add_argument("--telemetry-host", default=DEFAULT_TELEMETRY_HOST)
    setup_parser.add_argument("--origin", default=DEFAULT_ORIGIN)
    setup_parser.add_argument("--ngrok-auth-id", default=DEFAULT_NGROK_AUTH_ID)
    setup_parser.add_argument("--force", action="store_true")
    setup_parser.add_argument("--skip-install", action="store_true", help=argparse.SUPPRESS)
    setup_parser.set_defaults(handler=setup)

    doctor_parser = subparsers.add_parser("doctor", help="check USB, config, dependencies, and tunnel")
    doctor_parser.add_argument("--transport", choices=("auto", "frp", "ngrok"), default="auto")
    doctor_parser.set_defaults(handler=doctor_command)

    run_parser = subparsers.add_parser("run", help="run and supervise the gateway plus its tunnel")
    run_parser.add_argument("--transport", choices=("auto", "frp", "ngrok"), default="auto")
    run_parser.add_argument("--gateway", help="stable HTTPS gateway when using FRP")
    run_parser.add_argument("--ngrok-config", type=Path)
    run_parser.set_defaults(handler=supervise)

    smoke_parser = subparsers.add_parser("smoke", help="print the test URL and watch audit milestones")
    smoke_parser.add_argument("--gateway", help="public HTTPS gateway; otherwise discover local ngrok")
    smoke_parser.add_argument("--timeout", type=int, default=180)
    smoke_parser.add_argument("--open", action="store_true")
    smoke_parser.set_defaults(handler=smoke)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return int(args.handler(args))
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        print("remote-workbench:", error, file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
